/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.yy.tinytimes.thrift.mms.keywords;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Config implements org.apache.thrift.TBase<Config, Config._Fields>, java.io.Serializable, Cloneable, Comparable<Config> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Config");

  private static final org.apache.thrift.protocol.TField SEARCH_BY_KEYWORD_FIELD_DESC = new org.apache.thrift.protocol.TField("searchByKeyword", org.apache.thrift.protocol.TType.BOOL, (short)1);
  private static final org.apache.thrift.protocol.TField SEARCH_BY_REGULAR_FIELD_DESC = new org.apache.thrift.protocol.TField("searchByRegular", org.apache.thrift.protocol.TType.BOOL, (short)2);
  private static final org.apache.thrift.protocol.TField KEYWORD_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("keywordType", org.apache.thrift.protocol.TType.I32, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ConfigStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ConfigTupleSchemeFactory());
  }

  public boolean searchByKeyword; // required
  public boolean searchByRegular; // required
  public int keywordType; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SEARCH_BY_KEYWORD((short)1, "searchByKeyword"),
    SEARCH_BY_REGULAR((short)2, "searchByRegular"),
    KEYWORD_TYPE((short)3, "keywordType");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SEARCH_BY_KEYWORD
          return SEARCH_BY_KEYWORD;
        case 2: // SEARCH_BY_REGULAR
          return SEARCH_BY_REGULAR;
        case 3: // KEYWORD_TYPE
          return KEYWORD_TYPE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __SEARCHBYKEYWORD_ISSET_ID = 0;
  private static final int __SEARCHBYREGULAR_ISSET_ID = 1;
  private static final int __KEYWORDTYPE_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SEARCH_BY_KEYWORD, new org.apache.thrift.meta_data.FieldMetaData("searchByKeyword", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.SEARCH_BY_REGULAR, new org.apache.thrift.meta_data.FieldMetaData("searchByRegular", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.KEYWORD_TYPE, new org.apache.thrift.meta_data.FieldMetaData("keywordType", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Config.class, metaDataMap);
  }

  public Config() {
  }

  public Config(
    boolean searchByKeyword,
    boolean searchByRegular,
    int keywordType)
  {
    this();
    this.searchByKeyword = searchByKeyword;
    setSearchByKeywordIsSet(true);
    this.searchByRegular = searchByRegular;
    setSearchByRegularIsSet(true);
    this.keywordType = keywordType;
    setKeywordTypeIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Config(Config other) {
    __isset_bitfield = other.__isset_bitfield;
    this.searchByKeyword = other.searchByKeyword;
    this.searchByRegular = other.searchByRegular;
    this.keywordType = other.keywordType;
  }

  public Config deepCopy() {
    return new Config(this);
  }

  @Override
  public void clear() {
    setSearchByKeywordIsSet(false);
    this.searchByKeyword = false;
    setSearchByRegularIsSet(false);
    this.searchByRegular = false;
    setKeywordTypeIsSet(false);
    this.keywordType = 0;
  }

  public boolean isSearchByKeyword() {
    return this.searchByKeyword;
  }

  public Config setSearchByKeyword(boolean searchByKeyword) {
    this.searchByKeyword = searchByKeyword;
    setSearchByKeywordIsSet(true);
    return this;
  }

  public void unsetSearchByKeyword() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __SEARCHBYKEYWORD_ISSET_ID);
  }

  /** Returns true if field searchByKeyword is set (has been assigned a value) and false otherwise */
  public boolean isSetSearchByKeyword() {
    return EncodingUtils.testBit(__isset_bitfield, __SEARCHBYKEYWORD_ISSET_ID);
  }

  public void setSearchByKeywordIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __SEARCHBYKEYWORD_ISSET_ID, value);
  }

  public boolean isSearchByRegular() {
    return this.searchByRegular;
  }

  public Config setSearchByRegular(boolean searchByRegular) {
    this.searchByRegular = searchByRegular;
    setSearchByRegularIsSet(true);
    return this;
  }

  public void unsetSearchByRegular() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __SEARCHBYREGULAR_ISSET_ID);
  }

  /** Returns true if field searchByRegular is set (has been assigned a value) and false otherwise */
  public boolean isSetSearchByRegular() {
    return EncodingUtils.testBit(__isset_bitfield, __SEARCHBYREGULAR_ISSET_ID);
  }

  public void setSearchByRegularIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __SEARCHBYREGULAR_ISSET_ID, value);
  }

  public int getKeywordType() {
    return this.keywordType;
  }

  public Config setKeywordType(int keywordType) {
    this.keywordType = keywordType;
    setKeywordTypeIsSet(true);
    return this;
  }

  public void unsetKeywordType() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __KEYWORDTYPE_ISSET_ID);
  }

  /** Returns true if field keywordType is set (has been assigned a value) and false otherwise */
  public boolean isSetKeywordType() {
    return EncodingUtils.testBit(__isset_bitfield, __KEYWORDTYPE_ISSET_ID);
  }

  public void setKeywordTypeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __KEYWORDTYPE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case SEARCH_BY_KEYWORD:
      if (value == null) {
        unsetSearchByKeyword();
      } else {
        setSearchByKeyword((Boolean)value);
      }
      break;

    case SEARCH_BY_REGULAR:
      if (value == null) {
        unsetSearchByRegular();
      } else {
        setSearchByRegular((Boolean)value);
      }
      break;

    case KEYWORD_TYPE:
      if (value == null) {
        unsetKeywordType();
      } else {
        setKeywordType((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case SEARCH_BY_KEYWORD:
      return Boolean.valueOf(isSearchByKeyword());

    case SEARCH_BY_REGULAR:
      return Boolean.valueOf(isSearchByRegular());

    case KEYWORD_TYPE:
      return Integer.valueOf(getKeywordType());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case SEARCH_BY_KEYWORD:
      return isSetSearchByKeyword();
    case SEARCH_BY_REGULAR:
      return isSetSearchByRegular();
    case KEYWORD_TYPE:
      return isSetKeywordType();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Config)
      return this.equals((Config)that);
    return false;
  }

  public boolean equals(Config that) {
    if (that == null)
      return false;

    boolean this_present_searchByKeyword = true;
    boolean that_present_searchByKeyword = true;
    if (this_present_searchByKeyword || that_present_searchByKeyword) {
      if (!(this_present_searchByKeyword && that_present_searchByKeyword))
        return false;
      if (this.searchByKeyword != that.searchByKeyword)
        return false;
    }

    boolean this_present_searchByRegular = true;
    boolean that_present_searchByRegular = true;
    if (this_present_searchByRegular || that_present_searchByRegular) {
      if (!(this_present_searchByRegular && that_present_searchByRegular))
        return false;
      if (this.searchByRegular != that.searchByRegular)
        return false;
    }

    boolean this_present_keywordType = true;
    boolean that_present_keywordType = true;
    if (this_present_keywordType || that_present_keywordType) {
      if (!(this_present_keywordType && that_present_keywordType))
        return false;
      if (this.keywordType != that.keywordType)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(Config other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetSearchByKeyword()).compareTo(other.isSetSearchByKeyword());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSearchByKeyword()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.searchByKeyword, other.searchByKeyword);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSearchByRegular()).compareTo(other.isSetSearchByRegular());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSearchByRegular()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.searchByRegular, other.searchByRegular);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetKeywordType()).compareTo(other.isSetKeywordType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetKeywordType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.keywordType, other.keywordType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Config(");
    boolean first = true;

    sb.append("searchByKeyword:");
    sb.append(this.searchByKeyword);
    first = false;
    if (!first) sb.append(", ");
    sb.append("searchByRegular:");
    sb.append(this.searchByRegular);
    first = false;
    if (!first) sb.append(", ");
    sb.append("keywordType:");
    sb.append(this.keywordType);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ConfigStandardSchemeFactory implements SchemeFactory {
    public ConfigStandardScheme getScheme() {
      return new ConfigStandardScheme();
    }
  }

  private static class ConfigStandardScheme extends StandardScheme<Config> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Config struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SEARCH_BY_KEYWORD
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.searchByKeyword = iprot.readBool();
              struct.setSearchByKeywordIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SEARCH_BY_REGULAR
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.searchByRegular = iprot.readBool();
              struct.setSearchByRegularIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // KEYWORD_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.keywordType = iprot.readI32();
              struct.setKeywordTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Config struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(SEARCH_BY_KEYWORD_FIELD_DESC);
      oprot.writeBool(struct.searchByKeyword);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(SEARCH_BY_REGULAR_FIELD_DESC);
      oprot.writeBool(struct.searchByRegular);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(KEYWORD_TYPE_FIELD_DESC);
      oprot.writeI32(struct.keywordType);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ConfigTupleSchemeFactory implements SchemeFactory {
    public ConfigTupleScheme getScheme() {
      return new ConfigTupleScheme();
    }
  }

  private static class ConfigTupleScheme extends TupleScheme<Config> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Config struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetSearchByKeyword()) {
        optionals.set(0);
      }
      if (struct.isSetSearchByRegular()) {
        optionals.set(1);
      }
      if (struct.isSetKeywordType()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetSearchByKeyword()) {
        oprot.writeBool(struct.searchByKeyword);
      }
      if (struct.isSetSearchByRegular()) {
        oprot.writeBool(struct.searchByRegular);
      }
      if (struct.isSetKeywordType()) {
        oprot.writeI32(struct.keywordType);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Config struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.searchByKeyword = iprot.readBool();
        struct.setSearchByKeywordIsSet(true);
      }
      if (incoming.get(1)) {
        struct.searchByRegular = iprot.readBool();
        struct.setSearchByRegularIsSet(true);
      }
      if (incoming.get(2)) {
        struct.keywordType = iprot.readI32();
        struct.setKeywordTypeIsSet(true);
      }
    }
  }

}

